# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_gene_activities <- function(A, samples, consider_baseline_expression = TRUE, thread_no = 4L) {
    .Call(`_SCINET_compute_gene_activities`, A, samples, consider_baseline_expression, thread_no)
}

compute_gene_activities_decoupled <- function(archetypes, H, samples, consider_baseline_expression = TRUE, thread_no = 4L) {
    .Call(`_SCINET_compute_gene_activities_decoupled`, archetypes, H, samples, consider_baseline_expression, thread_no)
}

subsample_gene_activities <- function(A, rows, samples, total_subsamples = 30L, cells_per_subsample = 10L, thread_no = 4L, seed = 0L) {
    .Call(`_SCINET_subsample_gene_activities`, A, rows, samples, total_subsamples, cells_per_subsample, thread_no, seed)
}

subsample_gene_activities_decoupled <- function(archetypes, H, rows, samples, total_subsamples, cells_per_subsample, thread_no, seed) {
    .Call(`_SCINET_subsample_gene_activities_decoupled`, archetypes, H, rows, samples, total_subsamples, cells_per_subsample, thread_no, seed)
}

construct_cell_networks <- function(net, gene_activities, thread_no) {
    .Call(`_SCINET_construct_cell_networks`, net, gene_activities, thread_no)
}

construct_cell_networks_noPrior <- function(gene_activities, thread_no) {
    .Call(`_SCINET_construct_cell_networks_noPrior`, gene_activities, thread_no)
}

construct_cell_networks_summary <- function(net, gene_activities, total_subsamples = 30L, cells_per_subsample = 10L, seed = 0L, thread_no = 4L) {
    .Call(`_SCINET_construct_cell_networks_summary`, net, gene_activities, total_subsamples, cells_per_subsample, seed, thread_no)
}

